### ISSUE TITLE
implement #batch

### ISSUE THREAD

**Issue by catdad** [stezu/node-stream#8] opened 2017-01-04 00:36 UTC
Batch items being written to the stream, emitting an array of a specific length whenever that many items are read, and emitting all left-over items when the stream ends.

```javascrpit
ns.batch(count)
```

**Comment by stezu** [comment] 2017-01-07 03:12
I think this might end up being a dupe of #7 since the other reactive libraries treat them as similar methods. I'll leave this open until we figure out what to do for #7, but at least for now I don't think this issue is ready to be worked on.

**Comment by catdad** [comment] 2017-01-07 19:41
Yeah, the implementation is pretty much the same... it has different implications though (and really different use cases, I think). With throttle, we control for time, because we don't want the affect of the stream we are reading to happen too often. In batch, we control for the exact count of items, because we don't want to write too little at a time.

With that said, I did exactly zero research into this. Are you suggesting that we should allow one stream to throttle/batch based on either requirement or both? Examples:

`nodeStream.throttle({ count: 10 })` - emit an array of data once 10 items are collected

`nodeStream.throttle({ time: 100 })` - emit all data collected for 100 milliseconds since the last time data was emitted

`nodeStream.throttle({ count: 10, time: 100 })` - emit data when 10 elements are collected or 100 milliseconds have passed since the last data was written, whichever comes first

All options are optional, with the stream being just a plain passthrough when no options are defined?

**Closed** 2017-01-18 00:17 UTC
Labels: enhancement, in progress
